default_stages: [commit, push]
default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["src/backend", "--line-length", "100"]
        exclude: ^(.vscode/|.env/|deployment/|docs/|env/)
        types: ["python"]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        args: [--max-line-length=100, "--ignore", "E203,W503"]
        exclude: ^(.vscode/|build/|dist/|docs/|edgeapp.egg-info/)
        types: ["python"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^(.vscode/|build/|dist/|docs/|edgeapp.egg-info/)
        types: ["python"]
