# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SmartCamera


class PerceptionResultType(object):
    Unknown = 0
    Detection = 1
    Recognition = 2
    DetAndRec = 3
